### PR TITLE
feat: support static routes

### PR DESCRIPTION
**Pull request by PeterShershov**
Add `getStaticRoutes` to relevant routes in order to suggest data coming from an headless service on Codux's Pages Panel

### CODE REVIEW

**Review by nadav-ab — APPROVED** [review]

**Comment by PeterShershov** [comment]
@yurii-ve please review, should be merged to main as `getStaticRoutes` is already supported in Codux

**Comment by yurii-ve** [comment]
> @yurii-ve please review, should be merged to main as `getStaticRoutes` is already supported in Codux

@PeterShershov please see [PR comments](https://github.com/codux-templates/e-commerce-reclaim/pull/164/files) in the ReClaim template .. we'll copy functionality from there once it's merged

**Comment by PeterShershov** [comment]
@yurii-ve 👍 notice that @alisey merged my PR in reclaim.

**Comment by yurii-ve** [comment]
Closing in favour of https://github.com/codux-templates/e-commerce-remix/pull/102

**Pull request closed without merging**
